### ISSUE TITLE
fix eslinter errors after upgrading to `airbnb` shared config

### ISSUE THREAD

**Issue by jonknapp** [CoffeeAndCode/slipcast#9]
The `eslint` branch starts the change from the `coffeeandcode` shared eslint rules to `airbnb`. I've changed the dependencies, but there are a _ton_ of linter errors now.

Fix up the linter rules by adjusting the code _and_ by adding new `.eslintrc.json` overrides to the project folders when appropriate. (ex: some js files are browser es6 modules, others are node files for the cli or running tests)

**Comment by kobvel** [comment]
I did most of the job, but some things need additional discussion. Especially dynamic requires and console logging.

**Comment by jonknapp** [comment]
Closed with PR #11
